### ISSUE TITLE
Map points are not fetching incident category; showing up as 'undefined'

### ISSUE THREAD

**Issue by AWildColin** [thequbit/mc911feedwatcher#26]
![2015-02-02 09_22_04- default-1358568156634 monroe county ny 911 feed collator](https://cloud.githubusercontent.com/assets/1288116/6001973/0c835496-aabd-11e4-9ca2-1eec86f24bd1.png)

**Comment by thequbit** [comment]
Herm ... alright.

Thanks for the feedback, I'll look into this asap.

**Comment by thequbit** [comment]
Fixed, and pushed to production.  If it's working as you would expect just close the ticket!

Thanks again for the feedback :).

**Comment by AWildColin** [comment]
Confirmed, fixed in 39cccb41b. Closing.

**Comment by thequbit** [comment]
:+1:
